# Generated by Django 4.2.4 on 2023-08-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('rdate', models.DateField()),
                ('ramount', models.FloatField()),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.register')),
            ],
        ),
        migrations.CreateModel(
            name='Pledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pamount', models.FloatField()),
                ('option', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('periodic', 'periodic')], default='Weekly', max_length=10)),
                ('pdate', models.DateField()),
                ('fdate', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledge.register')),
            ],
        ),
    ]
